- Pipfile
- Pipfile.lock
- SIR-X.ipynb
- model.py
- post_regression.py
This pull request contains the same last commit of the confidence_interval branch, as I messed up dramatically the previous branch.
This PR contains:
1. Some style changes to model.py
2. An updated version of the **model.fit()** function, in order to be compatible with the changes included by @jia200x regarding storing the solution in the model object.
3. Two routines to calculate confidence intervals, contained in **post_regression.py**
3.1 sklearn is included in the pipfile as the bootstrapping method of confidence intervals require the sklearn resample functions
4. The Jupyter notebook was updated to reflect all previous changes
Following up a discussion with @jia200x, the confidence intervals routines will be part of the model class in the future. However, this will be part of a …
> feat(model): implement confidence intervals

- .circleci/config.yml
This PR removes the env variables check in the CircleCI `build` job. These env variables were not being exposed for forked PRs (security reasons), and were not really needed for this step.
> ci: remove env variables check when building Docker image

- tests/__init__.py
- tests/test_sir.py
**Branched from the [modules branch](https://github.com/open-sir/open-sir/tree/modules), see #22** 
After a bit of struggle, I started creating unit tests for the SIR model on the file tests/test_sir.py.
To create tests, create a file or write functions in the existing files which start with test_*
To run tests, 
`simplly pipenv run test`
1) **test_sixdays():**
Test predictions against Jupyter notebook case. The results are hard coded and the error is extected to be below the tolerance 1e-4.
2) **Exponential convergence**
A very famous test to the SIR model is to check whether the
one-parameter approximation
I ~ I_0 * exp (alpha-beta) as (S,t) -> (1,0)
Holds. This test implements it with a large population and short time
to ensure numerical consistency.
Note: this only holds for extremely …
> tests: add two tests to SIR

- Pipfile
- app.py
This removes the stub `app.py` script and uses the CLI application as entry-point for the pipenv script.
- Run `pipenv run start` and the CLI should be run.
> pipenv: Set CLI as 'start' script

- models/model.py
- models/sir.py
- models/sirx.py
This PR removes the `FUNC` variable to store the specific model, and adds a private "_model" member to extract that function.
It's required in order to merge #20
> refactor(model): use property to extract model

- tests/test_dummy.py
- tests/test_sir.py
This PR adds the basic test skeleton for writing tests with Pytest.
This PR uses a class based approach to write tests, and uses fixtures for creating the model.
It also removes the "test_dummy.py" file
> refactor(test_sir): migrate to basic skeleton

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
This PR adds templates for issues.
These templates were not invented by me, they are the default ones that GitHub suggests. We can add more in the future if we need them.
I will soon add a new PR for Pull Request templates too.
You can see a demo in this GIF:
> chore: add base issues templates

- .circleci/config.yml
- .gitignore
- Pipfile
- Pipfile.lock
- conf.py
- index.rst
- models/model.py
- models/sir.py
- models/sirx.py
This PR adds initial support for Sphinx documentation.
I suggest to read [this](https://brendanhasz.github.io/2019/01/05/sphinx.html) to have a better understanding of the usage The root file Sphinx file is the `index.rst`, from there we can include other files and module documentation.
To build the documentation:
- `pipenv run doc`
This command will call Sphinx's `make html` command to build HTML documentation. Other documentation formats are also available (man pages, latex, JSON, XML, etc).
The documentation is placed under `_build/html/index.html`
This PR also adds CircleCI build tests for the documentation, so we ensure the documentation is always consistent.
We need to slowly migrate all functions to their Sphinx format.
> docs: add sphinx documentation

- index.rst
This commit fixes the autoclass directives of the root Sphinx file.
They were pointing to "models.xxx" instead of "opensir.models.xxx"
> docs(sphinx): fix autoclass directives

- opensir/models/model.py
- opensir/models/sir.py
- opensir/models/sirx.py
This pull request enhances the model.fit() function in terms of its
accuracy and robustness:
In model.py, an special case for optimization is included for
the SIR-X model. One of the model parameters is the initial ratio
between infected and tested individuals, i_0/x_0. This is fitted
and require a slightly more careful treatment than traditional
parameter fitting. You can see the implementation on model.py fit
As I discovered this fifth parameter of sirx, I modified the sirx.py
class increasing the number of parameters to 5 and unpacking them
properly. Additionally, I included interesting quantities mentioned
in the paper of Maier et al (2020) such as the public containment
leverage P and the probability of quarantined Q. An effective r_0
and T_I are also defined. All of this was …
> feat(model): extend fit to SIR-X 

- Pipfile
This commit turns all `sphinx-build` warnings into errors.
The CI will now complain if the documentation is not build properly.
Without this commit, the `sphinx-build` exits with a successful error
code
> chore(sphinx): turn doc build warnings into errors

- Pipfile
- Pipfile.lock
- README.md
- opensir-cli
- opensir/models/model.py
- setup.py
This PR:
- Changes the old "ugly" input format to receive a TOML input file
- Adds "suppress header" and "delimiter" for formatting the CSV output.
```
usage: opensir-cli [-h] [-m {sir,sirx}] [-t TIME] [-f FILE] [-s] [-d DELIMITER]
Run SIR or SIR-X model given a set of initial conditions and model parameters.
optional arguments:
-h, --help            show this help message and exit
-m {sir,sirx}, --model {sir,sirx}
-t TIME, --time TIME  Number of days for the simulation
-f FILE, --file FILE  Name of the input file. If missing, the input file is read from STDIN
-s, --suppress_header
Suppress CSV header
-d DELIMITER, --delimiter DELIMITER
CSV delimiter
```
The input file is a TOML file with the following format
```
[initial_conds]
<cond> = value
[parameters]
<paran> = value
```
For …
> cli: improve CLI user experience

- .all-contributorsrc
This fixes the JSON to enable adding other contributors
> fix: JSON on .all-contributorsrc

- opensir/models/model.py
- opensir/models/sir.py
- opensir/models/sirx.py
- tests/test_model.py
This adds a check on the `set_params` method, to verify the correctness of the parameters. Also, I added some custom exceptions to raise on these cases.
I added just some simple tests on this. I changed `_set_params` to `set_params` and override that on the children, so testing can be done on the base model.
> model.py: Add checking on params and tests

- setup.py
In #44 @felipehuerta17 reported that windows is not being able to read the `README.md` for the package long description. #52 proposes not using the file, but it seems that just indicating the encoding in `open` is enough to make it work.
On Windows:
- on the repo run `pip install .` -> it should succeed.
Fixes #44
Alternative to #52
> setup.py: Specify encoding for long description

- .circleci/config.yml
- Dockerfile
- Pipfile
- Pipfile.lock
- README.md
- SIR.ipynb
- conf.py
- doc/conf.py
- index.rst
This PR:
- Adds the `nbsphinx` plugin to include Jupyter notebooks in Sphinx documentation
- Move the `index.rst` and `conf.py` to the root directory (unfortunately we will need to do this until someone finds a cleaner approach to import opensir outside of the root directory)
- Fix some style and import issues in the Jupyter notebook
- Include the notebook from Sphinx
- Add `pandoc` to Dockerfile (required by nbsphinx)
This indirectly adds some tests for Jupyter notebooks. If there's something wrong (style issues or wrong python code) then the documentation won't build (and CircleCI will complain)
Test with:
```
pipenv run doc
firefox doc/build/html
```
> nbsphinx: add Sphinx plugin to show Jupyter notebooks

- .readthedocs.yml
- README.md
- conf.py
- doc/getting-started.rst
- doc/requirements.txt
This PR adds the configuration needed for Read The Docs. It also introduces minor fixes needed to make it work. The changes are the ones tested in [this test branch](https://github.com/open-sir/open-sir/tree/read_the_docs), which produce [this documentation](https://open-sir.readthedocs.io/en/read_the_docs/).
We can't directly test changes from the PR. So, for testing all changes are mirrored in `read_the_docs` branch, and the documentation is built automatically.
> doc: Add 'Read The Docs' configuration

- doc/API.rst
- opensir/models/model.py
- opensir/models/sirx.py
In this PR I start the discussion and visualization on how well the documents will look like when including model descriptions on API.rst.
As API.rst is linked to the index of the html
Copy this branch, do pipenv run doc and look the pretty equations and tell me what you think, whether this is in the good direction or not.
In the functions documentation I also included an RST notation following OpenFOAM style. 
The idea is to throw the first stone, and make many commits more here to update the docs
> docs: include math description of models

- .github/workflows/wip_blocker.yml
This PR adds a GitHub action that runs whenever a PR pointing to `master` or `develop` (inexistent for the time being) is (un)labaled. When it runs, it checks that there is no "WIP" nor "blocked" string in neither the title of the PR, nor its labels.
I think it will only run once this has been merged to master.
> ci: block merges when PRs are titled/labeled with 'WIP' or 'blocked'

- opensir/models/model.py
- opensir/models/sir.py
- opensir/models/sirx.py
- tests/test_model.py
- tests/test_sir.py
This PR adds modifies the `set_params` function to accept dictionaries and lists.
This is a showcase of a non breaking API change, since it's still possible to use the old method (ordered lists).
However, I added a deprecation note that the list will be removed soon to support only dicts.
I also added some new tests for ensuring this change is safe and adopted the documentation.
As expected, this change shouldn't break any existing application.
If the proposed tests make sense, simply run `pipenv run test`.
> feat(model): add dict params to set_params function

- opensir/models/model.py
- tests/test_sirx.py
In response to #64, I begin writing SIR-X tests from the sir template that @jia200x created.
As SIR-X is mathematically more complex, the logical tests will be adapted but new mathematical tests will be implemented.
I will not test any .fit() functionality here as that will be a separate PR dealing with a potentially much more difficult issue.
> test(sirx): create sir-x tests

- .circleci/config.yml
This PR makes use of Docker image caching when building the Docker image. It makes the CI take 2 minutes less (and it was by far the longest job in the CI).
Basically, instead of trying to build the image from scratch every time, it downloads an already existing version of the same image, and tries to use cache from there.
> ci: cache Docker image builds

- opensir/models/model.py
- opensir/models/sir.py
- opensir/models/sirx.py
- tests/test_sir.py
This PR introduces 2 new functions for setting model parameters and initial conditions (see https://github.com/open-sir/open-sir/pull/61#issuecomment-614268738)
The old `set_params` function is still available, but added a deprecation note. We should migrate all examples to these new functions.
I also added some tests.
`pipenv run doc` and `pipenv run test`
Depends on #61
> feat: introduce `set_parametes` and `set_initial_conds` functions

- .circleci/config.yml
This PR adds a commit message linter job to CircleCI, to ensure that commit messages adhere to [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).
> ci: add a commitlint job

- .circleci/config.yml
- .markdownlint.json
- Pipfile
- README.md
This PR adds a linter job to the CI that checks if the `README.md` file follows [markdownlint](https://github.com/DavidAnson/markdownlint) conventions.
It seems it is a popular module, and used a lot by the community to enforce consistent markdown writing. As a matter of fact, all-contributors assumes its use (check for example the comments disabling markdownlint for auto-generated code).
atm I am blocking this branch waiting for https://github.com/open-sir/open-sir/pull/71 to be merged first.
Also, please do not auto-merge this. Let me do a rebase first.
> ci: add markdownlint to linter job

- .readthedocs.yml
This PR fixes the path of `conf.py` in the readthedocs YAML file.
With this change, readthedocs should be able to compile the documentation.
I will post a link with the RTD results
> fix(readthedocs): fix wrong location of conf.py

- doc/tutorials/SIR-X.ipynb
- doc/tutorials/SIR.ipynb
- opensir/models/model.py
- tests/test_model.py
Two new sets of tests were included for the model.fit function.
1. InconsistentDimensionError: raise an error whenever the
dimensions of input fitting data are not consistent. Can be
overloaded for other post regression functionalities.
2. InvalidInputsForFittingError: raised when either the
list of observed times or the list of number of infections 
are negative or non increasing.
Some piggybacking for casting lists to arrays for fit
inputs is also included, as this enables more efficient
exception testing.
These are non-breaking changes as they didn't affect the Jupyter notebooks examples.
If #63 gets merged before, I have no problem on updating some of the tests so
the mock model can be setup with the set_parameters and set_ic's.
>  test(model): create fit tests and improve fit validation

- doc/tutorials/SIR.ipynb
- opensir/models/post_regression.py
This PR changes the "options" parameter of both ci_xxx functions to explicit keyword arguments.
The rationale behind this is:
- Provide native Python defaults (e.g `ci_r0=True`)
- display a cleaner documentation
- Be able to modify only one default instead of all options at the same time
I also adapted the Jupyter to this change, so the documentation should still render OK.
Try building the documentation with `pipenv run doc`. The SIR.ipynb has some routines calling these functions, so it should be enough for now to check that the documentation is equivalent.
~Depends on #69~
> refactor(post_regression): change `option` parameter to explicit kwargs

- doc/tutorials/SIR-X.ipynb
- doc/tutorials/SIR.ipynb
- opensir/models/model.py
- opensir/models/post_regression.py
**Description**
This depends on #74 
This pull requests fixes the post regression routines that were previously valid only for the SIR model. Now, they can be used to any SIR-like model. 
model.py was again updated to include the attribute fit_index. As post-regression depends on regression, we ask the user to provide fit_index only the first time that she fits the model.
The SIR-X notebook was updated and now include a section on parameter fitting. This section is considerably longer and more explained than the one for the SIR model, as in SIR only one parameter was fitted while for SIR-X three parameters were fitted. Just as an interesting result, kappa_0 seems to be overfitting. I will create an issue with a wishlist for the next release, but we could add both the Akaike Information …
> fix: generalize confidence intervals

- doc/tutorials/SIR-X.ipynb
- doc/tutorials/SIR.ipynb
- opensir/models/model.py
- opensir/models/post_regression.py
- opensir/models/sir.py
- opensir/models/sirx.py
- tests/test_model.py
**Refactor fit and post regression functions to facilitate API usage & code testing**
Following the comments of @sasalatart on #76 regarding pylint complaining for the number of arguments, I refactored model, .fit and .set_params to ask for
parameters once. The typical usage of the API, as all our examples
show, follows this pipeline:
1. Build an empty model
2. Set parameters and initial conditions
3. Fit the model
4. Calculate confidence intervals.
Currently, we were asking the user for (t,X) on steps 3 and 4, and for the population on 3,4 but it was implicitely calculated on 2.  This PR refactors the code in a way that the population is calculated directly from the IC on 2, and we don't ask the user again twice. Additionally, (t,X) is asked only on step 3. This enables to ask the user …
> refactor(post_regression): ask parameters once and clarify pipeline

- doc/tutorials/SIR-X.ipynb
- doc/tutorials/SIR.ipynb
- opensir/models/model.py
- opensir/models/sir.py
- opensir/models/sirx.py
Equivalent to the [Utah Teapot](https://en.wikipedia.org/wiki/Utah_teapot)
`model.plot()` generates a plot from the calculated solution with the most relevant quantities for each of our models:
- SIR: (t vs I and R)
- SIR-X: (t vs I and X)
Calling `model.plot` requires the model to be either solved or fitted (because fitted -> solved).
Tests & updated README and docs will come soon. This will create a user friendly way for our users to validate the correct behaviour of open-sir against their parameters & fitting.
> feat(model): plot

- doc/tutorials/SIR-X.ipynb
- doc/tutorials/SIR.ipynb
- opensir/models/post_regression.py
This PR Depends on #77 
We had a 3.5h conversation with @jia200x yesterday and figured out a that the pipeline after fitting the model wasn't clean. First of all, we clarified the pipeline
-------
1. Create an empty model
2. Set IC and parameters
3. Fit the model
4. Calculate confidence interval -> CI Bootstrap
5. model.summary()
--------------------------
--------------------------
6. Predict (depends on .fit() )
7. Block cross validation to calculate 
8. Calculate a broader range of predictions
This PR focuses on *7* and *8*. 1-4 are done and *5* is optional *6* should be a wrapper over model.solve.
The user has actually few access to the amazing model performance quantities that block_cv is calculating. Following the refactor of #77 and the recently introduced PredictionResults …
> feat(predictionresults): print and plot
